services:
  web:
    build: ./web
    expose:
      - "5000"

  api:
    build: ./api
    expose:
      - "3001"
    environment:
      - FLASK_URL=http://web:5000
      - SERVICE2_URL=http://service2:3002
      - KAFKA_BROKER=kafka:9092
      - REDIS_URL=redis://redis:6379
    depends_on:
      - kafka
      - redis
      - web
      - service2

  service2:
    build: ./service2
    expose:
      - "3002"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: public.ecr.aws/docker/library/redis:7-alpine
    expose:
      - "6379"
    volumes:
      - redis_data:/data

  kafka:
    image: confluentinc/cp-kafka:7.8.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: EXTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://kafka:9092
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: "d33bd245-a018-40a3-91b1-b82cf89d9e1c"    
    volumes:
      - kafka_data:/tmp/kraft-combined-logs

  service3:
    build: ./service3
    expose:
      - "3003"
    environment:
      - KAFKA_BROKER=kafka:9092
      - REDIS_URL=redis://redis:6379
      - TRANSFORM_DELAY=1000
    depends_on:
      - kafka
      - redis

  front:
    build: ./front
    expose:
      - "80"
    environment:
      - REACT_APP_API_URL=

  nginx-proxy:
    build: ./proxy
    ports:
      - "80:80"
    volumes:
      - "/var/log/nginx:/var/log/nginx"
    depends_on:
      - web
      - api
      - front
      - service3

volumes:
  redis_data:
  kafka_data:
